<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>NU1902;NU1903;NU1904</NoWarn>
    <RootNamespace>BharatCMS.Domain</RootNamespace>
    <AssemblyName>BharatCMS.Domain</AssemblyName>
  </PropertyGroup>

</Project>